# Generated by Django 3.0.3 on 2020-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
