# Generated by Django 3.0.3 on 2020-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200303_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newcollection',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
